module.exports = [
    'longread',
    'elevator pitch',
    'minimum viable',
    'shift the needle',
    'our vertical',
    'new vertical',
    'new verticals',
    'pane of glass',
    'glass ceiling'
    'at the end of the day',
    'move the boat',
    'boat forward',
    'agility at scale',
    'scrum of scrums',
    'scaled agine',
    'disrupt the industry',
    'green field',
    'rockstar developer',
    'ninja developer',
    'rockstar developers',
    'ninja developers',
    'information technology',
    'I T',
    'drill down',
    'whiteboard this',
    'reach out to',
    'reaching out to',
    'true alignment',
    'comms cadence',
    'link authority',
    'thought leader',
    'thought leadership',
    'drive virality',
    'cranking out content',
    'more virality',
    'foster virality',
    'scale investment',
    'angel round',
    'ship shit',
    'shipping shit',
    'wall of innovation',
    'total cost of ownership',
    'return on investment',
    'weaponized speed',
    'machine learning',
    'implementation detail',
    'internet of things',
    'delight the user',
    'shiny new',
    'game changer',
    'change the game',
    'going forward',
    'move the needle',
    'enterprise grade',
    'take this offline',
    'outside the box',
    'cross platform',
    'best of breed',
    'growth strategies',
    'core competencies',
    'best practice',
    'future proof',
    'user centric',
    'early adopter',
    'late adopter',
    'one hundred and ten percent',
    '110 percent',
    '110%',
    'take it to the next level',
    'smack it out of the park',
    'smash it out of the park'
    'best in class',
    'scaling the platform',
    'will it scale',
    'web scale',
    'velocity project',
    'knowledge team',
    'our learnings',
    'the learnings',
    'people experience',
    'foster innovation',
    'one simple trick',
    'the one thing',
    'up the flag pole',
    'up the flagpole',
    'synergy',
    'cyber',
    'pushing the boat',
    'end of the beginning',
    'just getting started'
  ];
