module.exports = [
    'wall of innovation',
    'total cost of ownership',
    'return on investment',
    'weaponized speed',
    'machine learning',
    'implementation detail',
    'internet of things',
    'delight the user',
    'shiny new',
    'game changer',
    'change the game',
    'going forward',
    'move the needle',
    'take this offline',
    'outside the box',
    'cross platform',
    'best of breed',
    'growth strategies',
    'core competencies',
    'best practice',
    'future proof',
    'user centric',
    'early adopter',
    'late adopter',
    'one hundred and ten percent',
    '110 percent',
    '110%',
    'take it to the next level',
    'smack it out of the park',
    'best in class',
    'scaling the platform',
    'will it scale',
    'web scale',
    'velocity project',
    'knowledge team',
    'our learnings',
    'the learnings',
    'people experience',
    'foster innovation',
    'one simple trick',
    'the one thing',
    'up the flag pole',
    'up the flagpole',
    'synergy'
  ];
